---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: journalduhacker
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/custom-headers: "kube-system/kers-headers-noindex"
spec:
  tls:
    - hosts:
        - staging.jdh.pada.one
      secretName: jdh-tls
  rules:
    - host: staging.jdh.pada.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: journalduhacker
                port:
                  name: http
