apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jdh
resources:
  - namespace.yaml
  - ../base/
  - ingress-jdh.yaml
  - image-update-automation.yaml
  - secrets/rails-secretkeybase.yaml
  - deployment-mailpit.yaml
  - ingress-mailpit.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: journalduhacker
      spec:
        template:
          spec:
            containers:
              - name: journalduhacker
                env:
                  - name: SMTP_ADDRESS
                    value: mailpit.jdh.svc.cluster.local
                  - name: SMTP_PORT
                    value: "1025"
                  - name: SMTP_AUTHENTICATION
                    value: none
  - patch: |-
      apiVersion: k8s.mariadb.com/v1alpha1
      kind: MariaDB
      metadata:
        name: mariadb-jdh
      spec:
        replicas: 1
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 1Gi
        myCnf: |
          [mariadb]
          innodb_buffer_pool_size=800MB
images:
  - name: ghcr.io/flemzord/journalduhacker.net:unset
    newName: ghcr.io/flemzord/journalduhacker.net
    newTag: latest # {"$imagepolicy": "jdh:journalduhacker-staging:tag"}
    digest: sha256:3d30198bbaada679534a212c58e50ae4bcdeb1031df6f778d7195931374798a0 # {"$imagepolicy": "jdh:journalduhacker-staging:digest"}
