---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jdh
resources:
  - namespace.yaml
  - ../base/
  - ingress.yaml
  - image-update-automation.yaml

patches:
  # RÃ©duire les ressources pour staging
  - patch: |-
      apiVersion: k8s.mariadb.com/v1alpha1
      kind: MariaDB
      metadata:
        name: mariadb-jdh
      spec:
        replicas: 1
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 1Gi
        myCnf: |
          [mariadb]
          innodb_buffer_pool_size=800MB
  # Ajouter RAILS_ENV pour staging
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: journalduhacker
      spec:
        template:
          spec:
            containers:
              - name: journalduhacker
                env:
                  - name: RAILS_ENV
                    value: production

images:
  - name: ghcr.io/flemzord/journalduhacker.net:unset
    newName: ghcr.io/flemzord/journalduhacker.net
    newTag: main-d63cf80 # {"$imagepolicy": "jdh:journalduhacker-staging:tag"}
