apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jdh
resources:
  - namespace.yaml
  - ../base/
  - ingress.yaml
  - image-update-automation.yaml
  - secrets/
patches:
  # RÃ©duire les ressources pour staging
  - patch: |-
      apiVersion: k8s.mariadb.com/v1alpha1
      kind: MariaDB
      metadata:
        name: mariadb-jdh
      spec:
        replicas: 1
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 1Gi
        myCnf: |
          [mariadb]
          innodb_buffer_pool_size=800MB
images:
  - name: ghcr.io/flemzord/journalduhacker.net:unset
    newName: ghcr.io/flemzord/journalduhacker.net
    newTag: main-d63cf80 # {"$imagepolicy": "jdh:journalduhacker-staging:tag"}
    digest: sha256:e94d6bf2e5d0efdc415818c935bc4525bf7428ddf2bf2cc9161f37f4bcf52b05 # {"$imagepolicy": "jdh:journalduhacker-staging:digest"}
