apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jdh
resources:
  - namespace.yaml
  - ../base/
  #  - configmap-headers-noindex.yaml
  - ingress-jdh.yaml
  - image-update-automation.yaml
  - secrets/rails-secretkeybase.yaml
  - secrets/mailpit-auth.yaml
  - deployment-mailpit.yaml
  - ingress-mailpit.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mta
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: mta
                env:
                  - name: SMARTHOST
                    value: mailpit.jdh.svc.cluster.local::1025
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: journalduhacker
      spec:
        template:
          spec:
            initContainers:
              - name: db-migrate
                env:
                  - name: DATABASE_HOST
                    value: mariadb-jdh.jdh.svc.cluster.local
            containers:
              - name: journalduhacker
                env:
                  - name: DATABASE_HOST
                    value: mariadb-jdh.jdh.svc.cluster.local
  - patch: |-
      apiVersion: k8s.mariadb.com/v1alpha1
      kind: MariaDB
      metadata:
        name: mariadb-jdh
      spec:
        replicas: 1
        replication:
          enabled: false
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2
            memory: 1Gi
        myCnf: |
          [mariadb]
          innodb_buffer_pool_size=800MB
images:
  - name: ghcr.io/journalduhacker/journalduhacker.net:unset
    newName: ghcr.io/journalduhacker/journalduhacker.net
    newTag: latest # {"$imagepolicy": "jdh:journalduhacker-staging:tag"}
    digest: sha256:8a20e17ec105e01342d20401f26d6e920f87fb3493ac01391e70b34dd38a1c72 # {"$imagepolicy": "jdh:journalduhacker-staging:digest"}
