---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: journalduhacker-tmp
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - prod.jdh.pada.one
      secretName: jdh-tls
  rules:
    - host: prod.jdh.pada.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: journalduhacker
                port:
                  name: http
