---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: journalduhacker-redirect
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://www.journalduhacker.net/"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - journalduhacker.net
      secretName: jdh-tls-redirect
  rules:
    - host: journalduhacker.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: journalduhacker
                port:
                  name: http
