apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jdh
resources:
  - namespace.yaml
  - ../base/
  - ingress-jdh.yaml
  - image-update-automation.yaml
  - secrets/rails-secretkeybase.yaml
  - secrets/mta-smtp.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mta
      spec:
        template:
          spec:
            containers:
              - name: mta
                env:
                  - name: SMARTHOST
                    valueFrom:
                      secretKeyRef:
                        name: mta-smtp
                        key: SMARTHOST
                  - name: SMTP_USERNAME
                    valueFrom:
                      secretKeyRef:
                        name: mta-smtp
                        key: SMTP_USERNAME
                  - name: SMTP_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: mta-smtp
                        key: SMTP_PASSWORD
  - patch: |-
      apiVersion: k8s.mariadb.com/v1alpha1
      kind: MariaDB
      metadata:
        name: mariadb-jdh
      spec:
        replicas: 3
        replication:
          enabled: true
images:
  - name: ghcr.io/journalduhacker/journalduhacker.net:unset
    newName: ghcr.io/journalduhacker/journalduhacker.net
    newTag: v8.0.0 # {"$imagepolicy": "jdh:journalduhacker-production:tag"}
    digest: "" # {"$imagepolicy": "jdh:journalduhacker-production:digest"}
