apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jdh
resources:
  - namespace.yaml
  - ../base/
  - ingress-jdh.yaml
  - image-update-automation.yaml
  - secrets/rails-secretkeybase.yaml
images:
  - name: ghcr.io/journalduhacker/journalduhacker.net:unset
    newName: ghcr.io/journalduhacker/journalduhacker.net
    newTag: latest # {"$imagepolicy": "jdh:journalduhacker-production:tag"}
    digest: "" # {"$imagepolicy": "jdh:journalduhacker-production:digest"}
