---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: journalduhacker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: journalduhacker
  template:
    metadata:
      labels:
        app: journalduhacker
    spec:
      containers:
        - name: journalduhacker
          image: ghcr.io/flemzord/journalduhacker.net:unset
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DATABASE_NAME
              value: jdh
            - name: DATABASE_USER
              value: jdh
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-jdh-password
                  key: password
            - name: DATABASE_HOST
              value: mariadb-jdh.jdh.svc.cluster.local
            - name: RAILS_ENV
              value: production
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: journalduhacker-rails
                  key: secret-key-base
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: journalduhacker
spec:
  type: ClusterIP
  selector:
    app: journalduhacker
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
