---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database.yaml
  - deployment.yaml
  - image-repository.yaml

configMapGenerator:
  - name: mariadb-config-project
    files:
      - project.cnf=config/mariadb-config.ini
    options:
      # this option is used to avoid fluxcd to automatically restart the pod
      # when the configmap changes.
      disableNameSuffixHash: true
      labels:
        k8s.mariadb.com/watch: ""
